services:
  mongodb:
    image: mongo:7.0.11
    container_name: "mongoDB"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    volumes:
      - .data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mock-service-network

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    networks:
      - mock-service-network

networks:
  mock-service-network: